<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-7s5uDGW3AHqw6xtJmNNtr+OBRJUlgkNJEo78P4b0yRw= sha512-nNo+yCHEyn0smMxSswnf/OnX6/KwJuZTlNZBjauKhTK0c+zT+q5JOCx0UFhXQ6rJR9jg6Es8gPuD2uZcYDLqSw==" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha256-KXn5puMvxCw+dAYznun+drMdG1IFl3agK0p/pqT9KAo= sha512-2e8qq0ETcfWRI4HJBzQiA3UoyFk6tbNyG+qSaIBZLyW9Xf3sWZHN/lxe9fTh1U45DpPf07yj94KsUHHWe4Yk1A==" crossorigin="anonymous"></script>
<script type="application/javascript">
    jQuery(document).ready(function(){

    });
</script>
<?php
    if(!Mage::helper('postmarkapp')->isPostmarkEnabled()):
        echo ('
            <div class="alert alert-danger" role="alert">
              <strong>Warning!</strong> Postmark not enabled
            </div>
        ');

    else:
?>
<form class="form-inline">
    <div class="form-group">
        <label for="exampleInputName2">Date from</label>
        <input type="text" class="form-control" id="exampleInputName2" name="postmarkapp[fromdate]" placeholder="2015-12-24">
    </div>
    <div class="form-group">
        <label for="exampleInputEmail2">Date to</label>
        <input type="text" class="form-control" id="exampleInputName2" name="postmarkapp[fromdate]" placeholder="2015-12-31">
    </div>
    <button type="submit" class="btn btn-default">See emails</button>
</form>



<?php endif; ?>